name: Deploy Vue.js App to GitHub Pages

on:
  push:
    branches:
      - main  # Listens for changes on the `main` branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18  # Uses a version compatible with your project

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GH_TOKEN }}  # Use the secret token for authentication
        publish_branch: gh-pages
        publish_dir: ./dist

    - name: Configure git for deployment
      run: |
        git config --global user.name "LuisVad"
        git config --global user.email "20213tn002@utez.edu.mx"
